#ifndef FANN_FANN_CONF_H_
#define FANN_FANN_CONF_H_

#define SIGMOID_RESULTS_0 1
#define SIGMOID_RESULTS_1 1
#define SIGMOID_RESULTS_2 1
#define SIGMOID_RESULTS_3 1
#define SIGMOID_RESULTS_4 1
#define SIGMOID_RESULTS_5 1
#define SIGMOID_SYMMETRIC_RESULTS_0 -1
#define SIGMOID_SYMMETRIC_RESULTS_1 -1
#define SIGMOID_SYMMETRIC_RESULTS_2 -1
#define SIGMOID_SYMMETRIC_RESULTS_3 1
#define SIGMOID_SYMMETRIC_RESULTS_4 1
#define SIGMOID_SYMMETRIC_RESULTS_5 1
#define SIGMOID_VALUES_0 0
#define SIGMOID_SYMMETRIC_VALUES_0 -2
#define SIGMOID_VALUES_1 0
#define SIGMOID_SYMMETRIC_VALUES_1 -2
#define SIGMOID_VALUES_2 0
#define SIGMOID_SYMMETRIC_VALUES_2 -2
#define SIGMOID_VALUES_3 0
#define SIGMOID_SYMMETRIC_VALUES_3 2
#define SIGMOID_VALUES_4 0
#define SIGMOID_SYMMETRIC_VALUES_4 2
#define SIGMOID_VALUES_5 0
#define SIGMOID_SYMMETRIC_VALUES_5 2

#define NUM_NEURONS 139
#define MULTIPLIER 2
#define DECIMAL_POINT 1
#define NUM_INPUT 90
#define NUM_OUTPUT 3
#define NUM_LAYERS 3
#define CONNECTION_RATE 1.000000


#endif // FANN_FANN_CONF_H_
